language: c++

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

before_script:
  # OSX dependencies
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install exiv2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libraw; fi
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install quazip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi

  # Linux dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends debhelper cdbs libopencv-dev libhighgui-dev libcvaux-dev cmake qt55tools qt55svg qt55base qt5-image-formats-plugins libexiv2-dev libraw-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/"; fi

  - git clone --depth 1 http://github.com/nomacs/nomacs nomacs
  - git clone --depth 1 http://github.com/TUWien/ReadFramework ReadFramework
  - mkdir build
  - cd build
  - mkdir nomacs-build
  - mkdir readframework-build

script:
  - cd nomacs-build
  - cmake $CMAKE_ARGS ../../nomacs/ImageLounge
  # actually there is no need to build nomacs
  #- make -j8
  - cd ../readframework-build
  - cmake $CMAKE_ARGS ../../ReadFramework
  - make -j8
  - cd ..
  - cmake $CMAKE_ARGS -Dnomacs_DIR=./nomacs-build -DReadFramework_DIR=./ReadFramework ../.
  - make -j8
  
